config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title,
  presence: true,
  length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.reverse
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else  
      render 'new' ## It saves the state
      # redirect_to new_article_path ## It reloads the page
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>


<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<html>
  <head>
    <title>Blog Site</title>
  </head>
  <body>
    <h1>All Blog </h1>
    <% @articles.each do |article| %>
      <tr>
        <td>Title : <%= article.title %></td><br/>
        <td>Text : <%= article.text[0...10] %>...</td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <br/><br/><br/>
      </tr>
    <% end %>
    <%=link_to "Got to Welcome Page" , welcome_index_path %>
  </body>
</html>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>

</p>

<br>

<%= link_to 'Edit Blog', edit_article_path%>
<br/>
<%= link_to 'Delete Blog', @article , method: :delete, data: {confirm: "Are you sure ? "}%>
<br/>

<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<% @article.comments.each do |comment| %>
  <strong> <%= comment.commenter %> </strong>
  <p> <%= comment.body %> </p> 
  <%=link_to "Delete Comment", [comment.article, comment],method: :delete, data: {confirm: "Delete Comment ?"}%>
  <br/>
<%end%>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label 'commenter' %><br/>
    <%= form.text_field 'commenter' %>
  </p>

  <p>
    <%= form.label 'body' %><br/>
    <%= form.text_area 'body' %>
  </p>

  <p>
    <%= form.submit 'Comment'%>
  </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Welcome To Blog Site </h1>
<br/>
<%= link_to 'New Article', new_article_path %>
<br/>
<%= link_to "Visit My Blog", controller: 'articles' %>